# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edbeb53cd4c3213ba82646eefea8be1583bd6f65695516ba9d176ba2cdc96182abe964d5301a6722d37dada4a24d0cc1c96e4cdd747a85e0593870b8fae0f0c4

test:
  secret_key_base: 47274c66356f20c19e7c9160644893bc09f51061fdb574f12d93f01919ff98fc88c10fc238bb5005cf23a07aad1819f8d40949e19833a89f868b45d5061130b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
